version: "3.8"

services:
  porto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: porto-app
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads
    environment:
      - DATABASE_URL=file:./prisma/dev.db
      - NEXTAUTH_SECRET=portfolio-super-secret-key-change-in-production-2024
      - NEXTAUTH_URL=http://localhost:3000
    restart: always
